### ISSUE TITLE
Food search not working / Records missing AgencyName + Address

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/DDH_HomelessServices#29]
Selecting Food, Tomorrow, Search doesn’t do anything. I have a screen cap but can’t upload via phone

**Comment by gregallensworth** [comment]
Weird, and confrrmed. I am pretty sure this was working last time we used it!

When I do the search for *Food Tomorrow*, my debugger shows 21 results. However, the UI doesn't move forward, just stays at the search panel.

Same happens if I pick any *single topic* and then any day (Today, Tomorrow, Monday the 19th). Adding a second topic or more topics, the UI behaves as expected.

This appears to be some new bug/behavior related to choosing only one service.

**Comment by gregallensworth** [comment]
More info: This is NOT for any case of any single service, as I had noted previously.  Single-category searches for Food, Housing, Mental Health, and Phone (the ones I tried) all have the same buggy behavior. **resulting from their matching some provider records which are missing vital fields.**

It was never expected that one would create a provide record missing both its AgencyName and its Address. These seemed so basic that nobody would leave them blank...

**Comment by gregallensworth** [comment]
Two part fix:
* A workaround has been put into place, that if a record is missing the `AgencyName` and/or the `Address` then it will be silently skipped in the UI. After all, this wouldn't be a very useful result if it has neither a name nor an address.
* A new Issue is being opened to look over the records for those missing required fields, e.g. those mentioned above.
