### ISSUE TITLE
Details disappear on scroll 

### ISSUE THREAD

**Issue by danrademacher** [GreenInfo-Network/DDH_HomelessServices#39]
When I first look at this detail all is well:
![Image](https://i.imgur.com/SO4DbeP.jpg)

But then if I scroll the page, the description disappears:
![Image](https://i.imgur.com/9pAtOWH.jpg)

**Comment by gregallensworth** [comment]
This all ties back to the questionable design decision, of showing the panel at the bottom of the map, as if anchored to the bottom of the viewport. On small screens (our target audience) this doesn't work well.

See screenshots from iPhone 6 and 5 **emulators**. On the 6 the map is covered to a point that is no longer useful; on the 5 the entire screen is insufficient to show the detail narrative for this location, and when trying to do so the X to close this panel is right off the top of the screen.

The hack put into place was that the narrative description would only display if the screen is at least 55px tall. Not only does this not work well since iOS lies about viewport sizes, but it compromises the usefulness of the app if our target audience (older, small phones) cannot see relevant details (this shelter serves only youth or women).

*I would suggest moving the details into their own panel, and not the bottom-anchor thing. Given the volume of content in the narratives, this seems the best.*

**Comment by danrademacher** [comment]
How about this:

Basic "closed" view:
![image](https://user-images.githubusercontent.com/1423200/37796746-36ebdae8-2dd5-11e8-8431-928898cf7683.png)

Open view:
![image](https://user-images.githubusercontent.com/1423200/37797008-e3131c82-2dd5-11e8-8ab2-8e6847a003e6.png)

If you have another approach you want to take, go for it. I would like some way to see _some_ info at the same time as you see the map. Not just either/or.

**Comment by gregallensworth** [comment]
Per discussion: Let's keep the panels as-are, but add to them a `max-height` and scrolling behavior, so they can never dominate the whole screen, but we keep closely to the current behavior of seeing map + details at the same time, and quickly tapping map markers to view other details.

This could introduce a new UX wrinkle, as Android and IOS make scrollbars invisible so it may not be visibly obvious that the content will scroll. See what can be done about that, too?

**Comment by danrademacher** [comment]
Maybe just like this?
![image](https://user-images.githubusercontent.com/1423200/37797557-618b1474-2dd7-11e8-8c7f-ee4a9efbbb4d.png)

```css
    max-height: 40vh;
    overflow: scroll;
```

**Comment by gregallensworth** [comment]
New behavior implemented: a simple max-height & overflow-scroll.

Let's see how this tests. Only issue that "feels likely" is the invisible scrollbars.

**Comment by danrademacher** [comment]
NO issues from users, so closing this out
